{
 "title": "Home Treadmill",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "\"home-treadmill\"",
     "measure": "speed",
     "rawQuery": "SELECT time, measure_value::double as speed FROM $__database.$__table WHERE  measure_name='speed'",
     "table": "\"measurments\""
    }
   ]
  },
  {
   "title": "Latest Speed",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"home-treadmill\"",
     "measure": "speed",
     "rawQuery": "SELECT measure_value::double as speed FROM $__database.$__table ORDER BY time DESC LIMIT 1",
     "table": "\"measurments\""
    }
   ]
  },
  {
   "title": "Average Speed",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"home-treadmill\"",
     "measure": "speed",
     "rawQuery": "SELECT AVG(measure_value::double) FROM $__database.$__table WHERE measure_name='speed'",
     "table": "\"measurments\""
    }
   ]
  },
  {
   "title": "Max Speed",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"home-treadmill\"",
     "measure": "speed",
     "rawQuery": "SELECT MAX(measure_value::double) FROM $__database.$__table WHERE measure_name='speed'",
     "table": "\"measurments\""
    }
   ]
  }
 ]
}