AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AmazonGrafanaServiceRoleHomeTreadmill:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - grafana.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns: 
      - "arn:aws:iam::aws:policy/AmazonTimestreamReadOnlyAccess"

Outputs:
  RoleAwsAccountId:
    Value: !Ref AWS::AccountId
  RoleAwsRegion:
    Value: !Ref AWS::Region
  WorkspaceRoleToAssume:
    Value: !GetAtt AmazonGrafanaServiceRoleHomeTreadmill.Arn